# =========================================================
# CONFIGURATION FOR STARK-5S (CSLR PROJECT)
# =========================================================

# 2. Keypoint Streams (Phân chia 5 luồng theo CoSign) 
data:
  selected_total_points: 77
  streams:
    body: 
      indices: [0, 5, 6, 7, 8, 9, 10, 11, 12] # 9 điểm thân mình
      root_idx: 0 # Điểm gốc để thực hiện Centralization
    left_hand:
      indices: [91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111]
      root_idx: 91
    right_hand:
      indices: [112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]
      root_idx: 112
    mouth:
      indices: [71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82] 
      root_idx: 71
    face:
      indices: [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37] 
      root_idx: 24

