DSTA-Net:
  net: [[64, 64, 16, 7, 2], [64, 64, 16, 3, 1],
        [64, 128, 32, 3, 1], [128, 128, 32, 3, 1],
        [128, 256, 64, 3, 2], [256, 256, 64, 3, 1],
        [256, 256, 64, 3, 1], [256, 256, 64, 3, 1]]
  body_visual_head:
    input_size: 256
    hidden_size: 512
    ff_size: 2048
    pe: True
    ff_kernelsize: [3,3]
  left_visual_head:
    input_size: 256
    hidden_size: 512
    ff_size: 2048
    pe: True
    ff_kernelsize: [3,3]
  right_visual_head:
    input_size: 256
    hidden_size: 512
    ff_size: 2048
    pe: True
    ff_kernelsize: [3,3]
  fuse_visual_head:
    input_size: 1280
    hidden_size: 512
    ff_size: 2048
    pe: True
    ff_kernelsize: [3,3]
