data:
  # Đường dẫn tương đối - sử dụng cho mọi máy
  train_pkl: "C:/Users/TanHD6/Documents/DATN/data/phoenix-2014t/phoenix-2014t_cleaned.train"
  dev_pkl: "C:/Users/TanHD6/Documents/DATN/data/phoenix-2014t/phoenix-2014t_cleaned.dev"
  gloss_dict: "C:/Users/TanHD6/Documents/DATN/data/phoenix-2014t/gloss2ids.pkl"
  coords_root: "C:/Users/TanHD6/Documents/DATN/phoenix-npy_2"

model:
  # Input: 2212 coords * 3 features (pos, vel, acc) = 6636
  input_dim: 6636
  hidden_dim: 512
  num_lstm_layers: 3
  num_classes: 1124
  dropout: 0.2
  use_downsampling: true
  downsample_stride: 2

training:
  batch_size: 16
  learning_rate: 0.001
  epochs: 80
  save_path: "C:/Users/TanHD6/Documents/DATN/checkpoints_3"